Fall Banquet Info
cornellfencing/cornellfencing.github.io pull request #4
Opened 2017-08-01 04:40 UTC by amicableskeptic

Please merge and deploy if all looks good.

2017-08-01 17:24 UTC, NickHeiner commented on app/index.html
> +                   <p>For those who missed a chance to reunite with old friends and meet new, you are invited to our Fall Banquet Honoring the 1967 Women’s Championship Team, September 23, 2017 at th
Let's put a period at the end of the sentence "Register here".

2017-08-01 17:25 UTC, NickHeiner commented on app/index.html
> +                   <p>For those who missed a chance to reunite with old friends and meet new, you are invited to our Fall Banquet Honoring the 1967 Women’s Championship Team, September 23, 2017 at th
Just for fun, would you mind adding GA click tracking to these links? If that'll be too cumbersome, let me know, and I'll do it if I want it that badly. :smile:

2017-08-01 17:25 UTC, NickHeiner requested changes
Just one small change, then we can deploy.

2017-08-01 18:37 UTC, amicableskeptic commented on app/index.html
> +                   <p>For those who missed a chance to reunite with old friends and meet new, you are invited to our Fall Banquet Honoring the 1967 Women’s Championship Team, September 23, 2017 at th
I'm confused by this request. I looked at all the other links on the page and I don't see anything having been done to them to add GA click tracking. I then read Google's Set up Analytics tracking instructions (https://support.google.com/analytics/answer/1008080?hl=en) and they only talk about pasting the entire Javascript tracking-code snippet into your web page and not doing stuff to particular links. I checked and it looks like the GA snippet is in there. Am I missing something?

2017-08-02 02:06 UTC, NickHeiner commented
Also, I recommend that you make a feature branch and send PRs from that going forward, and keep your fork's `dev` as a mirror of the upstream `dev`. That should make your life easier.

2017-08-02 02:12 UTC, NickHeiner commented on app/index.html
> +                   <p>For those who missed a chance to reunite with old friends and meet new, you are invited to our Fall Banquet Honoring the 1967 Women’s Championship Team, September 23, 2017 at th
I see the GA network requests when the link is clicked, so I assume that we are tracking this. Sorry for the confusion.

2017-08-02 02:12 UTC, NickHeiner approved these changes

2017-08-02 02:13 UTC, merged

2017-08-02 02:14 UTC, NickHeiner commented
Deployed!