Fall Banquet 2017 Update
cornellfencing/cornellfencing.github.io pull request #7
Opened 2017-10-09 00:13 UTC by amicableskeptic

Adding post on Fall Dinner 2017 and doing a bunch of other small tweaks. Killing Archives and Spotlight on Fencers sections. Adding new email archives section.

2017-11-03 01:46 UTC, NickHeiner requested changes
Just a few changes, then this will be ready to go.

2017-11-03 01:46 UTC, NickHeiner commented on app/index.html
> +                   <img class="news-img" src="images/2017FallDinner.jpg" alt="Coaches with the 1967 Champions" />
Looks like you did not check in these images.

2017-11-03 01:46 UTC, NickHeiner commented on app/index.html
> +                       Mark your calendars now! The annual Cornell Fencing Spring Banquet has been scheduled for April 14, 2018. This years banquet we will be honoring Raoul Sudre in addition to fenc
> This years banquet we will be

This is missing at least an apostrophe. How about:

> This year's banquet, we will be

2017-11-03 01:46 UTC, NickHeiner commented on app/index.html
> +              <p>Cornell Fencing sends out regular email updates about how the program is doing. You can read through the e-mails that have been sent and subscribe to future ones by clicking <a href=
Click [here]()-style links tend to be worse for usability and accessibility. It's better to make the link be named for the thing that it's linking to. In this case, we could do:

> You can [read through the emails that have been sent and sign up for future ones]()

Or:

> You can read through the emails that have been sent and sign up for future ones on [our mailing list]().

2017-11-06 02:21 UTC, merged

2017-11-06 02:21 UTC, amicableskeptic commented
Check out my latest changes and deploy if everythign looks good.